---
- name: Converge
  hosts: molecule
  gather_facts: true

  tasks:
  - name: Install sudo
    ansible.builtin.package:
      name: sudo
      state: present
  - name: debug
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"